# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.5.5.post1.dev14+gb2c2598'
__version_tuple__ = version_tuple = (0, 5, 5, 'dev14', 'gb2c2598')
