---
blank_issues_enabled: false
contact_links:
  - name: NanoVNA-Saver Community Support
    url: https://github.com/zarath@gmx.de/nanovna-saver/discussions
    about: Please ask and answer questions here.
