name: Mac Release App

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  release:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Get Target Environment
      id: targetenv
      run: |        
        echo "arch=`uname -m`" >> "$GITHUB_ENV"

    - name: Install dependencies and pyinstall
      run: |
        python -m pip install pip==23.3.1 setuptools==68.2.2
        pip install -r requirements.txt
        pip install PyInstaller==6.2.0

    - name: Build binary
      run: |
        python setup.py -V        
        pyinstaller --onedir -p src -n NanoVNASaver nanovna-saver.py --window --clean  -y -i icon_48x48.icns
        tar -C dist -zcf ./dist/NanoVNASaver.app-${{ env.arch }}.tar.gz  NanoVNASaver.app
        echo "Created: NanoVNASaver.app-${{ env.arch }}.tar.gz"

    - name: Archive production artifacts
      uses: actions/upload-artifact@v1
      with:
        name: NanoVNASaver.app-${{ env.arch }}.tar.gz
        path: dist/NanoVNASaver.app-${{ env.arch }}.tar.gz
